"""empty message

Revision ID: 625c2de3bd5d
Revises: 31f8eb7215d1
Create Date: 2024-02-23 08:15:16.483760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625c2de3bd5d'
down_revision = '31f8eb7215d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerscandidates', schema=None) as batch_op:
        batch_op.alter_column('cover_letter',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerscandidates', schema=None) as batch_op:
        batch_op.alter_column('cover_letter',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
